### ISSUE TITLE
Test Deploy

### ISSUE THREAD

**Issue by Koro999** [Koro999/Library-Content-Manager#9]

**Comment by Koro999** [comment]
Deployment does have some directory issues because the main branch is missing routes.

**Comment by Koro999** [comment]
Second wave of deployment tests. Resolved an issue regarding branch merges being incorrect. Had to recorrect the files and remerge

**Comment by Koro999** [comment]
Getting issue on heroku:

Error: Cannot find module '/userRoutes'
2023-08-02T20:45:12.491957+00:00 app[web.1]: Require stack:
2023-08-02T20:45:12.491959+00:00 app[web.1]: - /app/controllers/index.js
2023-08-02T20:45:12.491961+00:00 app[web.1]: - /app/server.js
2023-08-02T20:45:12.491963+00:00 app[web.1]: at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-08-02T20:45:12.491964+00:00 app[web.1]: at Module._load (node:internal/modules/cjs/loader:922:27)
2023-08-02T20:45:12.491965+00:00 app[web.1]: at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-08-02T20:45:12.491965+00:00 app[web.1]: at require (node:internal/modules/cjs/helpers:110:18)
2023-08-02T20:45:12.491965+00:00 app[web.1]: at Object.<anonymous> (/app/controllers/index.js:3:20)
2023-08-02T20:45:12.491965+00:00 app[web.1]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-08-02T20:45:12.491965+00:00 app[web.1]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-08-02T20:45:12.491966+00:00 app[web.1]: at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-08-02T20:45:12.491966+00:00 app[web.1]: at Module._load (node:internal/modules/cjs/loader:960:12)
2023-08-02T20:45:12.491966+00:00 app[web.1]: at Module.require (node:internal/mod

Not sure why it cannot find the userRoute when it works completely fine on local. 

Checked casing and files names already.

**Comment by Koro999** [comment]
~ $ node seeds
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@faker-js/faker'
Require stack:
- /app/seeds/UserData.js
- /app/seeds/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/seeds/UserData.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/seeds/UserData.js', '/app/seeds/index.js' ]
}

Node.js v18.17.0

error seeding despite faker existing within the package.json under dependencies.

**Comment by Koro999** [comment]
Second wave of deploy works. Still running into faker issues with heroku.
